### ISSUE TITLE
WinJS Build error

### ISSUE THREAD

**Issue by deadlyfingers** [winjs/winjs#922]
I'm getting a different build error (using W10 preview)
### Fast Compile >>tests/WWA-Application/state.ts
Using tsc v1.0.1
C:\Users\user\git\winjs\node_modules\typescript\bin\tsc.js:906
                        vector.release();
                               ^
TypeError: undefined is not a function
    at BitMatrixImpl.release (C:\Users\user\git\winjs\node_modules\typescript\bin\tsc.js:906:32)

and...

Error: ENOENT, no such file or directory 'C:\Users\user\git\winjs\bin\tsbuild\WinJS\XYFocus.js'
In module tree:
    WinJS

{ [Error: Error: ENOENT, no such file or directory 'C:\Users\user\git\winjs\bin\tsbuild\WinJS\XYFocus.js'

**Comment by xirzec** [comment]
Weird, having trouble reproducing this locally. Can you compile any TypeScript projects?

**Comment by xirzec** [comment]
What version of node are you using? We ran into problems when using a Node version higher than 0.11.14.

**Comment by deadlyfingers** [comment]
Yes, it worked after downgrading node.js to v0.10.36 - I was using v0.12.0

**Comment by RyanCavanaugh** [comment]
Looks like this is a V8 bug relating to clearing sparse arrays by setting `length = 0`. We've confirmed it's broken in V8 3.28.73, works in 3.14.5.9, and works in 4.1.0.14 (io.js).

If needed you can manually patch tsc.js to work around the issue; instructions for typescript@1.0.1: 

Line 842 replace 
```
                this.bits.length = 0;
```
with
```
                this.bits.splice(0, this.bits.length);
```
And the same fix on line 910:
```
                this.vectors.length = 0;
```
replace with
```
                this.vectors.splice(0, this.vectors.length);
```

**Comment by cookiesowns** [comment]
It appears that this was fixed in node v0.12.4

Can anyone else confirm?

**Comment by dsherret** [comment]
I can confirm. Upgrading from node v0.12.2 to v0.12.4 fixed this for me.
